<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <title>Document</title>
</head>
<body>
    <h1>Asinronia en JS</h1>
    <script>
        function cuadradoPromesa(value){
            if(typeof(value)!== "number")return Promise.reject("Error el valor ingresado no es un numero.");
            return new Promise((resolve, reject)=> {
            setTimeout(() => {

                resolve({
                    value: value,
                    result: value*value
                });
               },0 | Math.random()*1000);
            })
        }   

            


            cuadradoPromesa(0)
            .then((obj) => {
                console.log("Inicia Promise")
                console.log(`Promise: ${obj.value}, ${obj.result}`);
                return cuadradoPromesa(1);
            })
            .then(obj => {
                console.log(`Promise: ${obj.value}, ${obj.result}`);
                return cuadradoPromesa(2);
            })
            .then(obj => {
                console.log(`Promise: ${obj.value}, ${obj.result}`);
                return cuadradoPromesa(3);
            })
            .then(obj => {
                console.log(`Promise: ${obj.value}, ${obj.result}`);
                return cuadradoPromesa(4);
            })
            .then(obj => {
                console.log(`Promise: ${obj.value}, ${obj.result}`);
                return cuadradoPromesa(5);
            })
            .then(obj => {
                console.log(`Promise: ${obj.value}, ${obj.result}`);
                console.log("Fin Promise")
            })
            .catch(err => console.error(err));

            //.catch(); es el metodo que va a capturar el error resultante del codigo.

            //.then() Proximo bloque de codigo que se va a ejecutar cuando se cumpla la funcion.
              
        
            function circuloPromesa(value){
                if(typeof(value) !== "number") return Promise.reject(`${value} is not a number`);

                return new Promise((resolve, reject) => {
                    setTimeout(() => {
                        resolve({
                        value:value,
                        result:value*value
                    })  
                    },0 | Math.random()*1000);
                })
            }

            circuloPromesa(1)
            .then(obj => {console.log("Inicio Promesa")
            console.log(`Promise: ${obj.value}, ${obj.result}`)
            }).catch(err => console.error(err));

    </script>
</body>
</html>